Title: CommunicatorCMS
Logo: "<img src='https://adamantica.com/projects/communicator-cms/icon.svg' style='width: 3.2rem; margin-right: 0.4rem'><span style='font-weight: normal; font-size: 2.2rem; font-family: Negatronic;'>CommunicatorCMS</span>"
Version: 1.0.0